name: rapid-api

on:
  schedule:
    - cron: 0 * * * *
  workflow_dispatch:

jobs:
  get-headline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Get Headline
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: https://newsapi.org/v2/top-headlines?language=en&pageSize=35&apiKey=6e9d9069fd6d4fad98e12e7e08d4967f

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main # Pushes the updates to the main branch.
          folder: fetch-api-data-action # The location of the data.json file saved by the Fetch API Data action.
          target-folder: data # Saves the data into the 'data' directory on the main branch.